######################
#   by MrKitty_Cat   #
#       Meowth!      #
######################

# If a value is not set, it will go to the default values.

SpyEnabled: "&dYour SpyMode is now &aEnabled!"

SpyDisabled: "&dYour SpyMode is now &cDisabled!"

GlobalEnabled: "&dYour GlobalChat is now &aEnabled!"

GlobalDisabled: "&dYour GlobalChat is now &cDisabled!"
